# Generated by Django 4.2.10 on 2024-02-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandados', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurados',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='procurados',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procurados',
            name='informacao_morte',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='procurados',
            name='origem_foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
