# Generated by Django 4.2.10 on 2024-02-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandados', '0003_alter_procurados_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurados',
            name='cnh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procurados',
            name='nis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procurados',
            name='rg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procurados',
            name='sap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
