# Generated by Django 4.2.10 on 2024-02-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandados', '0004_alter_procurados_cnh_alter_procurados_nis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurados',
            name='face_id_aws',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
