# Generated by Django 4.2.8 on 2023-12-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import presos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_esquerdo', models.ImageField(upload_to=presos.models.upload_to_perfil_esquerdo)),
                ('frontal', models.ImageField(upload_to=presos.models.upload_to_frontal)),
                ('perfil_direito', models.ImageField(upload_to=presos.models.upload_to_perfil_direito)),
                ('data_fotos', models.DateField()),
                ('origem_fotos', models.CharField(max_length=255)),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('mae', models.CharField(max_length=255)),
                ('pai', models.CharField(blank=True, max_length=255, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('uf_rg', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('nis', models.CharField(blank=True, max_length=20, null=True)),
                ('sap', models.CharField(blank=True, max_length=10, null=True)),
                ('razao_prisao', models.CharField(max_length=255)),
                ('numero_procedimento', models.CharField(max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
