# Generated by Django 4.2.10 on 2024-02-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preso',
            name='face_id_aws',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
