# Generated by Django 4.2.8 on 2023-12-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presos', '0002_preso_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preso',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
