# Generated by Django 4.2.8 on 2023-12-24 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presos', '0003_alter_preso_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preso',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preso',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
