# Generated by Django 4.2.9 on 2024-01-20 18:02

from django.db import migrations, models
import presos.models


class Migration(migrations.Migration):

    dependencies = [
        ('presos', '0005_preso_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='preso',
            name='alcunha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preso',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=presos.models.upload_to_avatar),
        ),
        migrations.AlterField(
            model_name='preso',
            name='frontal',
            field=models.ImageField(max_length=255, upload_to=presos.models.upload_to_frontal),
        ),
        migrations.AlterField(
            model_name='preso',
            name='perfil_direito',
            field=models.ImageField(max_length=255, upload_to=presos.models.upload_to_perfil_direito),
        ),
        migrations.AlterField(
            model_name='preso',
            name='perfil_esquerdo',
            field=models.ImageField(max_length=255, upload_to=presos.models.upload_to_perfil_esquerdo),
        ),
    ]
