# Generated by Django 4.2.9 on 2024-01-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presos', '0006_preso_alcunha_alter_preso_avatar_alter_preso_frontal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
