# Generated by Django 4.2.8 on 2023-12-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaspc',
            name='regional_vinculada',
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional', models.CharField(blank=True, max_length=200, null=True)),
                ('area_pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.areaspc')),
            ],
        ),
    ]
