# Generated by Django 4.2.8 on 2023-12-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_ibge', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('capital', models.BooleanField()),
                ('codigo_uf', models.IntegerField()),
                ('sigla_uf', models.CharField(max_length=2)),
                ('uf', models.CharField(max_length=100)),
                ('ddd', models.IntegerField()),
                ('fuso_horario', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('siafi_id', models.IntegerField()),
            ],
        ),
    ]
