# Generated by Django 4.2.8 on 2024-01-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas_apoio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo_iso', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
            },
        ),
    ]
