# Generated by Django 4.2.10 on 2024-02-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas_apoio', '0004_alter_idioma_options'),
        ('tabelas_apoio', '0005_popula_cidades'),
    ]

    operations = [
    ]
