# Generated by Django 4.2.10 on 2024-02-12 20:22

import django.core.validators
from django.db import migrations, models
import servidores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoElogiosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacao_elogiosa', models.TextField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, max_length=250, null=True)),
                ('data_anotacao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vinculo', models.CharField(blank=True, max_length=250, null=True)),
                ('cargo', models.CharField(blank=True, max_length=250, null=True)),
                ('cargo_atual', models.BooleanField(default=True)),
                ('data_inicio_vinculo', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, max_length=250, null=True)),
                ('classe_acesso', models.BooleanField(default=False)),
                ('classe_final', models.BooleanField(default=False)),
                ('data_classe', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Honraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honraria', models.CharField(blank=True, max_length=250, null=True)),
                ('origem', models.CharField(blank=True, max_length=250, null=True)),
                ('data_concessao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_local_trabalho', models.CharField(blank=True, max_length=250, null=True)),
                ('modalidade_lotacao', models.CharField(blank=True, max_length=250, null=True)),
                ('funcao', models.CharField(blank=True, max_length=250, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_lotacao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punicao', models.CharField(blank=True, max_length=250, null=True)),
                ('infracoes', models.TextField(blank=True, null=True)),
                ('data_punicao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_restricao', models.CharField(blank=True, max_length=250, null=True)),
                ('restricao', models.DateField(blank=True, null=True)),
                ('data_restricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_guerra', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=250, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('uf_naturalidade', models.CharField(blank=True, max_length=250, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', models.CharField(max_length=250, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve ter 11 dígitos.')])),
                ('rg', models.CharField(blank=True, max_length=250, null=True)),
                ('uf_rg', models.CharField(blank=True, max_length=250, null=True)),
                ('cnh', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria_cnh', models.CharField(blank=True, max_length=250, null=True)),
                ('primeira_habilitacao', models.DateField(blank=True, null=True)),
                ('vencimento_habilitacao', models.DateField(blank=True, null=True)),
                ('pis_pasep', models.CharField(blank=True, max_length=250, null=True)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=250, null=True)),
                ('zona_eleitoral', models.CharField(blank=True, max_length=250, null=True)),
                ('secao_eleitoral', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=250, null=True)),
                ('cor_pele', models.CharField(blank=True, max_length=250, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=250, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=250, null=True)),
                ('foto', models.ImageField(blank=True, max_length=250, null=True, upload_to=servidores.models.upload_foto_servidor)),
                ('avatar', models.ImageField(blank=True, max_length=250, null=True, upload_to=servidores.models.upload_avatar_servidor)),
                ('email_funcional', models.EmailField(max_length=254, unique=True)),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=250, null=True)),
                ('telefone_secundario', models.CharField(blank=True, max_length=250, null=True)),
                ('pessoa_emergencia', models.CharField(blank=True, max_length=250, null=True)),
                ('relacao_pessoa_emergencia', models.CharField(blank=True, max_length=250, null=True)),
                ('telefone_pessoa_emergencia', models.CharField(blank=True, max_length=250, null=True)),
                ('situacao_servidor', models.CharField(blank=True, max_length=250, null=True)),
                ('horario_reduzido', models.BooleanField(default=False)),
                ('motivo_horario_reduzido', models.CharField(blank=True, max_length=250, null=True)),
                ('data_inicio_horario_reduzido', models.DateField(blank=True, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=250, null=True)),
                ('religiao', models.CharField(blank=True, max_length=250, null=True)),
                ('tamanho_camisa', models.CharField(blank=True, max_length=250, null=True)),
                ('tamanho_colete', models.CharField(blank=True, max_length=250, null=True)),
                ('tamanho_calca', models.CharField(blank=True, max_length=250, null=True)),
                ('tamanho_calcado', models.CharField(blank=True, max_length=250, null=True)),
                ('quantidade_filhos', models.IntegerField(blank=True, null=True)),
                ('deficiencia', models.BooleanField(default=False)),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
    ]
