# Generated by Django 4.2.10 on 2024-02-12 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidades', '0001_initial'),
        ('tabelas_apoio', '0004_alter_idioma_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servidor',
            name='idiomas_secundarios',
            field=models.ManyToManyField(blank=True, to='tabelas_apoio.idioma'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restricao',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricao_incluida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restricao',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidores.servidor'),
        ),
        migrations.AddField(
            model_name='restricao',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricao_modificada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punicao',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punicao_incluida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='punicao',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidores.servidor'),
        ),
        migrations.AddField(
            model_name='punicao',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punicao_modificada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotacao_atribuida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades.unidades'),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidores.servidor'),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotacao_modificada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='honraria',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honraria_incluida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='honraria',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidores.servidor'),
        ),
        migrations.AddField(
            model_name='honraria',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honraria_modificada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classe_atribuida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidores.servidor'),
        ),
        migrations.AddField(
            model_name='classe',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classe_modificada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_criado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidores.servidor'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_modificado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anotacaoelogiosa',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacao_elogiosa_incluida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anotacaoelogiosa',
            name='servidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servidores.servidor'),
        ),
        migrations.AddField(
            model_name='anotacaoelogiosa',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotacao_elogiosa_modificada', to=settings.AUTH_USER_MODEL),
        ),
    ]
