# Generated by Django 4.2.9 on 2024-01-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_remove_servidor_idiomas_falados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
