# Generated by Django 4.2.9 on 2024-01-21 02:16

from django.db import migrations, models
import servidores.models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0004_servidor_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='avatar',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=servidores.models.upload_avatar_servidor),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=servidores.models.upload_foto_servidor),
        ),
    ]
